apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: nginx
  namespace: nginx
spec:
  interval: 5h
  chart: nginx-ingress
  sourceRef:
    kind: HelmRepository
    name: nginx
  version: '2.3.*'